package org.yyym.model.manager;

public enum GroupSource {
    DEFAULT_PLAYER1_CARTOON_L, DEFAULT_PLAYER1_CARTOON_R, DEFAULT_PLAYER1_CARTOON_T, DEFAULT_PLAYER1_CARTOON_B,
    DEFAULT_PLAYER2_CARTOON_L, DEFAULT_PLAYER2_CARTOON_R, DEFAULT_PLAYER2_CARTOON_T, DEFAULT_PLAYER2_CARTOON_B;
}
